Traceback (most recent call last):
  File "main.py", line 171, in check_for_updates
    parse_mode='HTML')
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/bot.py", line 258, in send_message
    timeout=timeout, **kwargs)
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py", line 238, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long
04 Nov 18:57:32

Traceback (most recent call last):
  File "main.py", line 171, in check_for_updates
    parse_mode='HTML')
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/bot.py", line 258, in send_message
    timeout=timeout, **kwargs)
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/Users/cmlimm/anaconda3/lib/python3.7/site-packages/telegram/utils/request.py", line 238, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long
04 Nov 18:57:51

